#include "sort.hpp"

#define RECOMMENDED_DIST_FROM_OCC_SITES 1
#define RECOMMENDED_DIST_FROM_EMPTY_SITES 0.1
#define MIN_DIST_FROM_OCC_SITES 1
#define MAX_SUBMOVE_DIST_IN_PENALIZED_AREA 1.5
#define COL_SPACING 0.5
#define ROW_SPACING 1
#define HALF_COL_SPACING ((double)(COL_SPACING) / 2)
#define HALF_ROW_SPACING ((double)(ROW_SPACING) / 2)